# Copy this file to .env for local development and fill in real values locally.
# Do not commit .env.

APP_ENV=development
FLASK_ENV=development
SECRET_KEY=dev-local-insecure-secret-key

ADMIN_EMAIL=founder@clarionhq.co
ADMIN_USERNAME=admin
ADMIN_PASSWORD=changeme123
FIRM_NAME=Example Law Firm

DATABASE_PATH=feedback.db

MAIL_ENABLED=0
MAIL_SERVER=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USE_TLS=1
MAIL_USE_SSL=0
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_DEFAULT_SENDER=no-reply@example.com

RESEND_API_KEY=
RESEND_FROM_EMAIL=

STRIPE_PUBLISHABLE_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_ID_TEAM_MONTHLY=
STRIPE_PRICE_ID_TEAM_ANNUAL=
STRIPE_PRICE_ID_FIRM_MONTHLY=
STRIPE_PRICE_ID_FIRM_ANNUAL=

FREE_TRIAL_LIMIT=1
TEAM_MONTHLY_PRICE=179
TEAM_ANNUAL_PRICE=1790
FIRM_MONTHLY_PRICE=449
FIRM_ANNUAL_PRICE=4490
ONETIME_REPORT_PRICE=49

REDIS_URL=
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
